# Generated by Django 3.1.2 on 2020-10-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Foto de Perfil'),
        ),
    ]
